export const tokens = {
  colors: {
    'border-light': '#D1D5DB',
    'primary-dark': '#0B1F3A',
    'text-primary': '#0B1F3A',
    'neutral-white': '#FFFFFF',
    'text-secondary': '#4A5568',
    'accent-positive': '#C9A24B',
    'status-negative': '#C0392B',
    'status-positive': '#2E7D46',
    'neutral-light-gray': '#EEF0F3',
  },
  typography: {
    'font-family-base': "'Inter', sans-serif",
    'font-family-numeric': "'Space Mono', monospace",
    'font-size-h1': '2.5rem',
    'font-size-h2': '2rem',
    'font-size-h3': '1.5rem',
    'font-size-body-base': '1rem',
    'font-size-body-large': '1.125rem',
    'font-size-body-small': '0.875rem',
    'font-weight-bold': '700',
    'font-weight-medium': '500',
    'font-weight-regular': '400',
    'line-height-base': '1.5',
  },
  spacing: {
    'xs': '8px',
    'sm': '16px',
    'md': '24px',
    'lg': '32px',
    'xl': '48px',
    'xxl': '64px',
  },
  borderRadius: {
    'sm': '4px',
    'md': '6px',
    'lg': '10px',
    'full': '9999px',
  },
  shadows: {
    'sm': '0px 1px 3px rgba(0, 0, 0, 0.1)',
    'md': '0px 4px 6px rgba(0, 0, 0, 0.1)',
  },
  motion: {
    'easing-standard': 'ease-in-out',
    'transition-duration-fast': '150ms',
    'transition-duration-normal': '300ms',
  },
};
